name = "ndinteractive/lute_watch"
version = "0.2.0"
description = "A path watcher for Lute"
authors = ["9e4ches"]
repository = "https://github.com/nd-interactive/lute-watch"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**", "LICENSE", ".luaurc"]

[target]
environment = "luau"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"
